import type {Localization} from "./components/project/Project.tsx";

export const localizations: Localization[] = [
  { id: "af_za", name: "Afrikaans - Suid-Afrika" },
  { id: "ar_sa", name: "Arabic - العربية (العالم العربي)" },
  { id: "ast_es", name: "Asturian - Asturianu (Asturies)" },
  { id: "az_az", name: "Azerbaijani - Azərbaycanca (Azərbaycan)" },
  { id: "ba_ru", name: "Bashkir - Башҡортса (Башҡортостан, Рәсәй)" },
  { id: "bar", name: "Bavarian - Boarisch (Bayern)" },
  { id: "be_by", name: "Belarusian (Cyrillic) - Беларуская (Беларусь)" },
  { id: "be_latn", name: "Belarusian (Latin) - Biełaruskaja (Biełaruś)" },
  { id: "bg_bg", name: "Bulgarian - Български (България)" },
  { id: "br_fr", name: "Breton - Brezhoneg (Breizh)" },
  { id: "brb", name: "Brabantian - Braobans (Braobant)" },
  { id: "bs_ba", name: "Bosnian - Bosanski (Bosna i Hercegovina)" },
  { id: "ca_es", name: "Catalan - Català (Catalunya)" },
  { id: "cs_cz", name: "Czech - Čeština (Česko)" },
  { id: "cy_gb", name: "Welsh - Cymraeg (Cymru)" },
  { id: "da_dk", name: "Danish - Dansk (Danmark)" },
  { id: "de_at", name: "Austrian German - Deitsch (Österreich)" },
  { id: "de_ch", name: "Swiss German - Schwiizerdutsch (Schwiiz)" },
  { id: "de_de", name: "German - Deutsch (Deutschland)" },
  { id: "el_gr", name: "Greek - Ελληνικά (Ελλάδα)" },
  { id: "en_au", name: "Australian English - English (Australia)" },
  { id: "en_ca", name: "Canadian English - English (Canada)" },
  { id: "en_gb", name: "British English - English (United Kingdom)" },
  { id: "en_nz", name: "New Zealand English - English (New Zealand)" },
  { id: "en_pt", name: "Pirate English - Pirate Speak (The Seven Seas)" },
  { id: "en_ud", name: "Upside Down English - ɥsᴉꞁᵷuƎ (uʍoᗡ ǝpᴉ)" },
  { id: "en_us", name: "American English - English (United States)" },
  { id: "eo", name: "Esperanto" },
  { id: "es_ar", name: "Argentinian Spanish - Español (Argentina)" },
  { id: "es_cl", name: "Chilean Spanish - Español (Chile)" },
  { id: "es_co", name: "Colombian Spanish - Español (Colombia)" },
  { id: "es_es", name: "Spanish - Español (España)" },
  { id: "es_mx", name: "Mexican Spanish - Español (México)" },
  { id: "es_uy", name: "Uruguayan Spanish - Español (Uruguay)" },
  { id: "es_ve", name: "Venezuelan Spanish - Español (Venezuela)" },
  { id: "et_ee", name: "Estonian - Eesti (Eesti)" },
  { id: "eu_es", name: "Basque - Euskara (Euskal Herria)" },
  { id: "fa_ir", name: "Persian - فارسی (ایران)" },
  { id: "fi_fi", name: "Finnish - Suomi (Suomi)" },
  { id: "fo_fo", name: "Faroese - Føroyskt (Føroyar)" },
  { id: "fr_be", name: "Belgian French - Français (Belgique)" },
  { id: "fr_ca", name: "Canadian French - Français (Canada)" },
  { id: "fr_ch", name: "Swiss French - Français (Suisse)" },
  { id: "fr_fr", name: "French - Français (France)" },
  { id: "frp", name: "Arpitan - Arpetan (Arpitania)" },
  { id: "fur_it", name: "Friulian - Furlan (Friûl)" },
  { id: "fy_nl", name: "Frisian - Frysk (Fryslân)" },
  { id: "ga_ie", name: "Irish - Gaeilge (Éire)" },
  { id: "gd_gb", name: "Scottish Gaelic - Gàidhlig (Alba)" },
  { id: "gl_es", name: "Galician - Galego (Galicia)" },
  { id: "gu_in", name: "Gujarati - ગુજરાતી (ભારત)" },
  { id: "haw_us", name: "Hawaiian - ʻŌlelo Hawaiʻi (Hawaiʻi)" },
  { id: "he_il", name: "Hebrew - עברית (ישראל)" },
  { id: "hi_in", name: "Hindi - हिन्दी (भारत)" },
  { id: "hr_hr", name: "Croatian - Hrvatski (Hrvatska)" },
  { id: "hsb", name: "Upper Sorbian - Hornjoserbšćina (Serbja)" },
  { id: "hu_hu", name: "Hungarian - Magyar (Magyarország)" },
  { id: "hy_am", name: "Armenian - Հայերեն (Հայաստան)" },
  { id: "ia", name: "Interlingua" },
  { id: "id_id", name: "Indonesian - Bahasa Indonesia (Indonesia)" },
  { id: "is_is", name: "Icelandic - Íslenska (Ísland)" },
  { id: "it_ch", name: "Swiss Italian - Italiano (Svizzera)" },
  { id: "it_it", name: "Italian - Italiano (Italia)" },
  { id: "ja_jp", name: "Japanese - 日本語 (日本)" },
  { id: "jbo", name: "Lojban - la .lojban." },
  { id: "jv_id", name: "Javanese - ꦧꦱꦗꦮ (Indonesia)" },
  { id: "ka_ge", name: "Georgian - ქართული (საქართველო)" },
  { id: "kab_dz", name: "Kabyle - Taqbaylit (Taqvaylit)" },
  { id: "kk_kz", name: "Kazakh - Қазақша (Қазақстан)" },
  { id: "kn_in", name: "Kannada - ಕನ್ನಡ (ಭಾರತ)" },
  { id: "ko_kr", name: "Korean - 한국어 (대한민국)" },
  { id: "ku", name: "Kurdish - Kurdî" },
  { id: "ky_kg", name: "Kyrgyz - Кыргызча (Кыргызстан)" },
  { id: "la", name: "Latin - Latina" },
  { id: "lb_lu", name: "Luxembourgish - Lëtzebuergesch (Lëtzebuerg)" },
  { id: "li", name: "Limburgish - Limburgs" },
  { id: "lij_it", name: "Ligurian - Ligure (Liguria)" },
  { id: "lt_lt", name: "Lithuanian - Lietuvių (Lietuva)" },
  { id: "lv_lv", name: "Latvian - Latviešu (Latvija)" },
  { id: "mai", name: "Maithili - मैथिली" },
  { id: "mg_mg", name: "Malagasy - Malagasy (Madagasikara)" },
  { id: "mi", name: "Maori - Te Reo Māori" },
  { id: "mk_mk", name: "Macedonian - Македонски (Македонија)" },
  { id: "ml_in", name: "Malayalam - മലയാളം (ഇന്ത്യ)" },
  { id: "mn_mn", name: "Mongolian - Монгол хэл (Монгол)" },
  { id: "mr_in", name: "Marathi - मराठी (भारत)" },
  { id: "ms_my", name: "Malay - Bahasa Melayu (Malaysia)" },
  { id: "mt_mt", name: "Maltese - Malti (Malta)" },
  { id: "my_mm", name: "Burmese - မြန်မာ (မြန်မာ)" },
  { id: "nb_no", name: "Norwegian Bokmål - Norsk bokmål (Norge)" },
  { id: "ne_np", name: "Nepali - नेपाली (नेपाल)" },
  { id: "nl_be", name: "Belgian Dutch - Nederlands (België)" },
  { id: "nl_nl", name: "Dutch - Nederlands (Nederland)" },
  { id: "nn_no", name: "Norwegian Nynorsk - Norsk nynorsk (Noreg)" },
  { id: "oc_fr", name: "Occitan - Occitan (Occitània)" },
  { id: "or_in", name: "Odia - ଓଡ଼ିଆ (ଭାରତ)" },
  { id: "pa_in", name: "Punjabi - ਪੰਜਾਬੀ (ਭਾਰਤ)" },
  { id: "pl_pl", name: "Polish - Polski (Polska)" },
  { id: "ps_af", name: "Pashto - پښتو (افغانستان)" },
  { id: "pt_br", name: "Brazilian Portuguese - Português (Brasil)" },
  { id: "pt_pt", name: "Portuguese - Português (Portugal)" },
  { id: "quz_pe", name: "Quechua - Runa Simi (Perú)" },
  { id: "ro_ro", name: "Romanian - Română (România)" },
  { id: "ru_ru", name: "Russian - Русский (Россия)" },
  { id: "rw_rw", name: "Kinyarwanda - Ikinyarwanda (Rwanda)" },
  { id: "se_no", name: "Northern Sami - Davvisámegiella (Norgga)" },
  { id: "si_lk", name: "Sinhala - සිංහල (ශ්‍රී ලංකාව)" },
  { id: "sk_sk", name: "Slovak - Slovenčina (Slovensko)" },
  { id: "sl_si", name: "Slovenian - Slovenščina (Slovenija)" },
  { id: "so_so", name: "Somali - Soomaali (Soomaaliya)" },
  { id: "sq_al", name: "Albanian - Shqip (Shqipëri)" },
  { id: "sr_sp", name: "Serbian - Српски (Србија)" },
  { id: "sv_se", name: "Swedish - Svenska (Sverige)" },
  { id: "sw_ke", name: "Swahili - Kiswahili (Kenya)" },
  { id: "ta_in", name: "Tamil - தமிழ் (இந்தியா)" },
  { id: "te_in", name: "Telugu - తెలుగు (భారతదేశం)" },
  { id: "tg_tj", name: "Tajik - Тоҷикӣ (Тоҷикистон)" },
  { id: "th_th", name: "Thai - ไทย (ประเทศไทย)" },
  { id: "tk_tm", name: "Turkmen - Türkmen (Türkmenistan)" },
  { id: "tl", name: "Tagalog" },
  { id: "tn_bw", name: "Tswana - Setswana (Botswana)" },
  { id: "tr_tr", name: "Turkish - Türkçe (Türkiye)" },
  { id: "tt_ru", name: "Tatar - Татарча (Россия)" },
  { id: "ug_cn", name: "Uyghur - ئۇيغۇرچە (جۇڭگو)" },
  { id: "uk_ua", name: "Ukrainian - Українська (Україна)" },
  { id: "ur_pk", name: "Urdu - اردو (پاکستان)" },
  { id: "uz_uz", name: "Uzbek - Oʻzbekcha (Oʻzbekiston)" },
  { id: "vi_vn", name: "Vietnamese - Tiếng Việt (Việt Nam)" },
  { id: "xh_za", name: "Xhosa - isiXhosa (iMzantsi Afrika)" },
  { id: "yo_ng", name: "Yoruba - Yorùbá (Nàìjíríà)" },
  { id: "zh_cn", name: "Simplified Chinese - 简体中文 (中国)" },
  { id: "zh_tw", name: "Traditional Chinese - 繁體中文 (台灣)" },
  { id: "zu_za", name: "Zulu - isiZulu (iNingizimu Afrika)" }
]
